# -----------------
# Site Information
# -----------------
title: "Jinmma12's DevLog"
description: "Archive"
url: "https://jinmma12.github.io"
avatar: "/assets/images/profile.png" # ⬅️ assets/images/ 폴더에 profile.png 파일을 넣어주세요.
# 'plugins' 목록은 수정하지 마세요.
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

# -----------------
# Author Information
# -----------------
author:
  name: Jinmma12
  job: "Software Engineer"
  location: Seoul, South Korea
  email: "acoodow12@gmail.com" # ⬅️ 공개할 이메일이 있다면 여기에 입력하세요.
  links:
    - name: GitHub
      url: https://github.com/jinmma12
      icon: fab fa-github
    # - name: LinkedIn
    #   url: https://...
    #   icon: fab fa-linkedin

# -----------------
# Style
# -----------------
skin: "blue" # ⬅️ Blue & White 테마 적용

# -----------------
# Build settings
# -----------------
# 아래 부분은 특별한 경우가 아니면 수정하지 않아도 됩니다.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  style: compressed
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - vendor

# -----------------
# Menus
# -----------------
# 상단 메뉴 설정
menus:
  - title: "Home"
    url: "/"
  - title: "Categories"
    url: "/categories"
  - title: "Tags"
    url: "/tags"
  - title: "About"
    url: "/about"